# Generated by Django 3.2.12 on 2022-02-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.RemoveField(
            model_name='player',
            name='created',
        ),
        migrations.AddField(
            model_name='player',
            name='wordlist',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
